<h2>Produkt list</h2>
<a href = '/admin/product/add/'>přidat nový produkt</a>
<table>
    <thead>
        <tr>
            <th>název produktu</th>
            <th>cena</th>
            <th>množství</th>
            <th>detail produktu</th>
            <th>do košíku</th>
        </tr>
        
        <?php
        foreach($products as $product){?>
            <tr>                              
                <td><?php echo $product["name"] ?></td>
                <td><?php echo $product["price"] ?></td>
                <td><?php echo $product["mount"] ?></td>
                <td><?php echo "<a href = \"/product/detail/$product[id]\">detail produktu</a>" ?></td>
                <td>    
                    <?php include('/../../forms/cartItemUpdateForm.phtml')?>
                </td>
            </tr>    
        <?php } //endforeach ?>

        </tr>        
    </thead>
</table>