<h2>Produkt list</h2>
<a href = '/admin/product/add/'>přidat nový produkt</a><br /><br />
<table>
    <thead>
        <tr>
            <th>název produktu</th>
            <th>cena</th>
            <th>množství</th>
            <th>aktivni</th>
            <th>detail produktu</th>
            <th>editovat produkt</th>
            <th>smazat produkt</th>
        </tr>
        
        <?php
        foreach($products as $product){?>
            <tr>                              
                <td><?php echo $product["name"] ?></td>
                <td><?php echo $product["price"] ?></td>
                <td><?php echo $product["mount"] ?></td>
                <td><?php echo $product["is_active"] ?></td>
                <td><?php echo "<a href = \"/admin/product/detail/$product[id]\">detail produktu</a>" ?></td>
                <td><?php echo "<a href = \"/admin/product/edit/$product[id]\">editovat produkt</a>" ?></td>
                <td><?php echo "<a href = \"/admin/product/delete/$product[id]\" onclick=\"return confirmMsg('Opravdu chcete produkt smazat?')\">smazat produkt</a>" ?></td>
            </tr>    
        <?php } //endforeach ?>

        </tr>        
    </thead>
</table>