<!DOCTYPE html>
<html>
    <head>
        <title> Vizus E-shop <?php if(isset($title)) echo "| ".$title ?></title>
        <meta charset="UTF-8">
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <meta http-equiv="Content-language" content="cs">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Josef Jakub Jestřáb"/>
        <meta name="copyright" content="(c) 2016 VIZUS.CZ s.r.o."
        <meta name="Robots" content="none"/>
        <link rel="stylesheet" href="/css/style.css">
    </head>
    <body>
        <div id = header>
            <h1>Vizus E-shop Admin</h1><br />
            <?php if(isset($_SESSION['username'])){?> <a href="/admin/prihlaseni/logout" title="odhhlásit y admina">odhlásit se</a> <?php }?>
            <div id = "info"><p><?php if(isset($info)) echo $info; ?></p></div>
        </div>            
            <div class = "w100" id = "main">
                <div id = "content">
                    
                    
                    <?php 
                    if(isset($view))
                        include("$view.phtml");
                    ?>
                    
                </div>    
            </div>
            <p class = "p10"><a href="http://www.vizus.cz/" title="VIZUS – tvorba www stránek">VIZUS</a> | <a href="http://www.vizus.cz/webmaster/">webmaster</a> | Zde zatím nepoužíváme <a href="http://www.vizus.cz/produkty/cms/" title="Redakční systém Vizus CMS">redakční systém Vizus CMS</a></p>
    </body>
</html>

