<form action="/admin/prihlaseni/potvrzeni" method="post">
    
        <label for="username"><strong>Uživatelské jméno: </strong></label><input type="text" name="username" pattern="^([\wá-žÁ-Ž\s \.])+$" autofocus="autofocus" required ><br />
        <label for="password"><strong>Heslo: </strong></label><input type="password" name="password" required><br />
        
        <input type='hidden' name='csrf_token' value='<?php echo $_SESSION["csrf_token"]; ?>' />
        <div class ="nor"><label for ="e-mail">nevyplňujte prosím: </label><input type="text" name="e-mail" value=""></div>
        <input type="submit" value="Přihlásit"/>
        
</form>

