<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.0 setup script
 * Date: Sat, 28 Apr 2012 19:20:06 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['PmaAbsoluteUri'] = 'https://'.php_uname('n').'/dbtools/phpmyadmin3/';
$cfg['blowfish_secret'] = 'g2PK58F6y458b3C6wdp3U87';
$cfg['DefaultLang'] = 'cs';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['LeftFrameDBTree'] = false;
?>