<ul class="pagination">
    <?php
    if($pagination_actual_page === 1) 
    { 
      echo "<li><div>«</div></li>";        
    }
    else
    {
        echo "<li><a href='/produkt/list/".($pagination_actual_page - 1) ."' disabled>«</a></li>"; 
    }    
    ?> 

    <?php for($i = 1; $i <= $pagination_count;$i++)
    {  
        echo "<li><a href='/produkt/list/".$i ."'"; 
        
        if($i === $pagination_actual_page)
        {
            echo "class='active'";
        }
        
        echo ">".$i ."</a></li>";
    } 
    if($pagination_actual_page === $pagination_count) 
    { 
        echo "<li><div>»</div></li>";        
    }
    else
    {
        echo "<li><a href='/produkt/list/".($pagination_actual_page + 1) ."' >»</a></li>"; 
    }    
    ?> 
     
</ul>