<div class = "fright"><a href = "/kosik/" title ="přejít do košíku">Košík</a></div>

<h2>Produkt list</h2>
<?php include('/../../forms/sortTableForm.phtml')?>
<?php if(!empty($products)){ ?>
    <table>
        <thead>
            <tr>
                <th>název produktu</th>
                <th>cena</th>
                <th>množství</th>
                <th>detail produktu</th>
                <th>do košíku</th>
            </tr>

            <?php
            foreach($products as $product){?>
                <tr>                              
                    <td><?php echo $product["name"] ?></td>
                    <td><?php echo $product["price"] ?></td>
                    <td><?php echo $product["mount"] ?></td>
                    <td><?php echo "<a href = \"/produkt/detail/$product[id]\">detail produktu</a>" ?></td>
                    <td>    
                        <?php include('/../../forms/cartItemUpdateForm.phtml')?>
                    </td>
                </tr>    
            <?php } //endforeach ?>

            </tr>        
        </thead>
    </table>
    <?php if(isset($pagination_count)){ 
        include('@pagination.phtml');
    }    
} else {?>
<p>V tuto chvíli nejsou k dispozici žádné produkty</p>
<?php } ?>
